main/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from main import views as app_views


urlpatterns = [
    url(r'^$', app_views.home, name='home'),

    # Componentes
    url(r'^componentes/data/$', app_views.ComponenteJson.as_view(), name="componente_data"),
    url(r'^componentes/$', app_views.ComponenteList.as_view(), name="componente_list"),
    url(r'^componentes/create/$', app_views.ComponenteCreate.as_view(), name="componente_create"),
    url(r'^componentes/(?P<pk>\d+)/editar/$', app_views.ComponenteUpdate.as_view(), name="componente_update"),
    url(r'^componentes/eliminar/$', app_views.ComponenteDelete.as_view(), name="componente_delete"),

    # Auditoria de componentes
    url(r'^componentes/auditoria/data/$', app_views.ComponenteAuditoriaJson.as_view(),
        name="componente_auditoria_data"),
    url(r'^componentes/auditoria/$', app_views.ComponenteAuditoriaList.as_view(), name="componente_auditoria_list"),
    url(r'^componentes/auditoria/(?P<pk>\d+)/$', app_views.ComponenteAuditoriaDetail.as_view(),
        name="componente_auditoria_detail"),
]

proyecto/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from main import urls as app_urls
from perfiles import urls as perfil_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('two_factor.urls', 'two_factor')),
    url(r'^account/', include('allauth.urls')),
    url(r'', include(app_urls)),
    url(r'^profile/', include(perfil_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models/componente.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import ManyToManyField


class Componente(models.Model):
    TIPO_COMPONENTE = (
        (1, 'Activo'),
        (2, 'Excipiente'),
    )

    responsable = models.ForeignKey(User, related_name='componentes', verbose_name='Responsable')
    nombre_comercial = models.CharField(max_length=50, unique=True, verbose_name='Nombre Comercial')
    iupac = models.CharField(max_length=50, unique=True, verbose_name='IUPAC')
    unii = models.CharField(max_length=25, unique=True, verbose_name='UNII')
    formula = models.CharField(max_length=50, verbose_name='Formula')
    peso_molecular = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name='Peso Molecular')
    biodisponibilidad = models.CharField(max_length=25, blank=True, null=True, verbose_name='Biodisponibilidad')
    union_proteica = models.CharField(max_length=25, blank=True, null=True, verbose_name='Union Proteica')
    metabolismo = models.CharField(max_length=25, blank=True, null=True, verbose_name='Metabolismo')
    vida_media = models.CharField(max_length=25, blank=True, null=True, verbose_name='Vida Media')
    excrecion = models.CharField(max_length=25, blank=True, null=True, verbose_name='Excrecion')
    via_admon = models.CharField(max_length=50, verbose_name='Via de Administracion')
    tipo = models.PositiveSmallIntegerField(choices=TIPO_COMPONENTE, verbose_name='Tipo')

    creado = models.DateTimeField(auto_now_add=True, verbose_name='Creado')
    fecha_firma = models.DateTimeField(auto_now=True, verbose_name='Fecha Firma')
    firma = models.TextField(blank=True, null=True, verbose_name='Firma Electronica')

    class Meta:
        app_label = 'main'
        verbose_name = 'Componente'
        verbose_name_plural = 'Componentes'

    def __str__(self):
        return '%s - %s' % (self.unii, self.nombre_comercial)

    def to_dict(self):
        opts = self._meta
        data = {}
        for f in opts.concrete_fields + opts.many_to_many:
            if isinstance(f, ManyToManyField):
                if self.pk is None:
                    data[f.name] = []
                else:
                    data[f.name] = list(f.value_from_object(self).values_list('pk', flat=True))
            else:
                data[f.name] = str(f.value_from_object(self))
        return data

main/models/componente_auditoria.py
from django.contrib.auth.models import User
from django.db import models

from main.models import Componente


class ComponenteAuditoria(models.Model):
    CREADO = 1
    EDITADO = 2
    ELIMINADO = 3

    TIPO_ACCION = (
        (CREADO, 'Creado'),
        (EDITADO, 'Editado'),
        (ELIMINADO, 'Eliminado'),
    )

    componente = models.ForeignKey(Componente, related_name='pistas_auditoria', verbose_name='Componente')
    usuario = models.ForeignKey(User, related_name='componentes_auditoria', verbose_name='Usuario')
    contenido = models.TextField(verbose_name='Contenido')
    firma = models.TextField(verbose_name='Firma Electrónica')
    fecha = models.DateTimeField(auto_now_add=True, verbose_name='Fecha')
    descripcion = models.TextField(verbose_name='Descripcion')
    accion = models.SmallIntegerField(choices=TIPO_ACCION, verbose_name='Accion')

    class Meta:
        app_label = 'main'
        verbose_name = 'Auditoria de Componente'
        verbose_name_plural = 'Auditoria de Componentes'

    def __str__(self):
        return '%s' % self.componente

main/models/perfil.py
from django.db import models
from django.contrib.auth.models import User


class Perfil(models.Model):
    usuario = models.OneToOneField(User, related_name='perfil', verbose_name='Usuario')

    class Meta:
        app_label = 'main'
        verbose_name = 'perfil'
        verbose_name_plural = 'perfiles'

    def __str__(self):
        return '%s' % self.usuario

main/forms/componente.py
from django import forms

from main.forms import FieldSetModelFormMixin
from main.models.componente import Componente


class ComponenteForm(FieldSetModelFormMixin):
    password = forms.CharField(widget=forms.PasswordInput, label='Contraseña (Firmar)')

    class Meta:
        model = Componente
        fields = [
            'id', 'nombre_comercial', 'iupac', 'unii', 'formula', 'peso_molecular', 'biodisponibilidad',
            'union_proteica', 'metabolismo', 'vida_media', 'excrecion', 'via_admon', 'tipo'
        ]


class ComponenteUpdateForm(ComponenteForm):
    descripcion = forms.CharField(widget=forms.Textarea, label='Motivo de la Edicion')

main/forms/mixins.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Fieldset
from django import forms


class FieldSetModelFormMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(FieldSetModelFormMixin, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 col-form-label'
        self.helper.field_class = 'col-sm-10'
        self.helper.wrapper_class = 'form-group row'
        self.field_names = self.fields.keys()

    def set_legend(self, text):
        self.helper.layout = Fieldset(text, *self.field_names)

    def set_action(self, action):
        self.helper.form_action = action

main/views/componente.py
import decimal
import json

from django.core import signing
from django.contrib.auth import authenticate
from django.core.exceptions import ObjectDoesNotExist
from django.forms import model_to_dict
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from django.shortcuts import render, redirect, get_object_or_404
from django.db import transaction
from django.contrib import messages
from django_datatables_view.base_datatable_view import BaseDatatableView
from two_factor.views import OTPRequiredMixin

from main.forms import ComponenteForm
from main.forms.componente import ComponenteUpdateForm
from main.models import Componente, ComponenteAuditoria


class ComponenteJson(OTPRequiredMixin, BaseDatatableView):
    model = Componente
    columns = ['id', 'unii', 'iupac', 'nombre_comercial', 'tipo']
    order_columns = ['id', 'unii', 'iupac', 'nombre_comercial', 'tipo']


class ComponenteList(OTPRequiredMixin, TemplateView):
    template_name = 'componentes/list.html'


class ComponenteCreate(OTPRequiredMixin, CreateView):
    model = Componente
    template_name = 'componentes/create.html'
    success_url = reverse_lazy('componente_create')
    form_class = ComponenteForm

    def post(self, request, *args, **kwargs):
        password = request.POST.get('password', '')
        form = ComponenteForm(request.POST)
        componente = form.save(commit=False)

        user = authenticate(username=request.user.username, password=password)

        if user is not None:
            with transaction.atomic():
                # asignamos el usuario y firmamos el componente
                componente.responsable = user
                componente.save()
                serialized = componente.to_dict()
                componente.firma = signing.dumps(serialized, salt=password)
                componente.save()
                auditoria = ComponenteAuditoria(
                    componente=componente,
                    usuario=user,
                    contenido=serialized,
                    accion=ComponenteAuditoria.CREADO,
                    firma=componente.firma,
                    descripcion='Componente creado'
                )

                auditoria.save()
                messages.add_message(request, messages.SUCCESS, 'Componente creado de forma correcta')
                return redirect('componente_list')

        return render(request, 'componentes/create.html', {'form': form})


class ComponenteUpdate(OTPRequiredMixin, UpdateView):
    model = Componente
    form_class = ComponenteUpdateForm
    template_name = 'componentes/update.html'
    success_url = reverse_lazy('componente_list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        password = request.POST.get('password', '')
        descripcion = request.POST.get('descripcion', '')
        form = ComponenteForm(request.POST, instance=self.object)
        componente = form.save(commit=False)

        user = authenticate(username=request.user.username, password=password)

        if user is not None:
            with transaction.atomic():
                # asignamos el usuario y firmamos el componente
                componente.responsable = user
                componente.save()
                serialized = componente.to_dict()
                componente.firma = signing.dumps(serialized, salt=password)
                componente.save()

                auditoria = ComponenteAuditoria(
                    componente=componente,
                    usuario=user,
                    contenido=serialized,
                    accion=ComponenteAuditoria.EDITADO,
                    firma=componente.firma,
                    descripcion=descripcion
                )
                auditoria.save()

                messages.add_message(request, messages.WARNING, 'Componente editado de forma correcta')
                return redirect('componente_list')

        return render(request, 'componentes/update.html', {'form': form})


class ComponenteDelete(OTPRequiredMixin, TemplateView):
    def post(self, request):
        componente_id = request.POST.get('id', 0)
        componente = Componente.objects.get(pk=componente_id)
        if componente:
            componente.delete()
            return JsonResponse({'result': 'OK', 'message': 'Componente eliminado'})

        return JsonResponse({'result': 'ERROR', 'message': 'Componente inválido'}, status=404)

main/views/componente_auditoria.py
from django.views.generic import TemplateView, DetailView
from django_datatables_view.base_datatable_view import BaseDatatableView
from two_factor.views import OTPRequiredMixin

from main.models import ComponenteAuditoria


class ComponenteAuditoriaJson(OTPRequiredMixin, BaseDatatableView):
    model = ComponenteAuditoria
    columns = ['id', 'componente.nombre_comercial', 'componente.unii', 'accion', 'fecha']
    order_columns = ['id', 'componente.nombre_comercial', 'componente.unii', 'accion', 'fecha']


class ComponenteAuditoriaList(OTPRequiredMixin, TemplateView):
    template_name = 'componentes_auditoria/list.html'


class ComponenteAuditoriaDetail(OTPRequiredMixin, DetailView):
    model = ComponenteAuditoria
    template_name = 'componentes_auditoria/detail.html'

main/views/home.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from two_factor.utils import default_device


@login_required
def home(request):
    return render(request, 'home.html', {'default_device': default_device(request.user)})

main/templates/componentes_auditoria/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content_header %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
        <li class="breadcrumb-item"><a href="{% url 'componente_list' %}">Componentes</a></li>
        <li class="breadcrumb-item"><a href="{% url 'componente_auditoria_list' %}">Pistas de Auditoria</a></li>
        <li class="breadcrumb-item active">Detalle</li>
    </ol>
{% endblock %}

{% block content %}
    <div id="ui-view">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col">
                    <div class="card card-accent-warning">
                        <div class="card-header">
                            <i class="fa fa-edit"></i>Pista de Auditoria del Componente
                        </div>
                        <div class="card-body">
                            <p>
                                <b>Componente:</b><br />
                                {{ object.componente }}
                            </p>
                            <hr />
                            <p>
                                <b>Usuario:</b><br />
                                {{ object.usuario.first_name }} {{ object.usuario.last_name }}
                            </p>
                            <hr />
                            <p>
                                <b>Accion:</b><br />
                                {{ object.get_accion_display }}
                            </p>
                            <hr />
                            <p>
                                <b>Fecha:</b><br />
                                {{ object.fecha }}
                            </p>
                            <hr />
                            <p>
                                <b>Descripcion de la Accion:</b>
                                <blockquote class="blockquote firma">
                                    <p class="mb-0">{{ object.descripcion }}</p>
                                </blockquote>
                            </p>
                            <hr />
                            <p>
                                <b>Contenido Original:</b>
                                <blockquote class="blockquote firma">
                                    <p class="mb-0">{{ object.contenido }}</p>
                                </blockquote>
                            </p>
                            <hr />
                            <p>
                                <b>Firma Electrónica:</b>
                                <blockquote class="blockquote firma">
                                    <p class="mb-0">{{ object.firma }}</p>
                                    <footer class="blockquote-footer">
                                        Firmado por <b>{{ object.usuario.first_name }} {{ object.usuario.last_name }}</b> el {{ object.fecha }}
                                    </footer>
                                </blockquote>
                            </p>
                        </div>
                        <div class="card-footer">
                            <div class="text-right">
                                <a class="btn btn-secondary" href="{% url 'componente_auditoria_list' %}">
                                    <i class="fa fa-arrow-left"></i> Volver
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/componentes_auditoria/list.html
{% extends "base.html" %}
{% load static from staticfiles %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'datatables.net-bs4/css/dataTables.bootstrap4.css' %}">
{% endblock %}

{% block content_header %}
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
        <li class="breadcrumb-item"><a href="{% url 'componente_list' %}">Componentes</a></li>
        <li class="breadcrumb-item">Pistas de Auditoria</li>
    </ol>
{% endblock %}

{% block content %}
    <div id="ui-view">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col">
                    <div class="card card-accent-warning">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> Pistas de Auditoria para Componentes
                        </div>
                        <div class="card-body">
                            <div class="row justify-content-between">
                                <div class="col-6">
                                    <div class="input-group">
                                        <input id="search" type="text" class="form-control" placeholder="Buscar....."
                                               aria-label="Buscar">
                                    </div>
                                </div>
                                <div class="col-2">
                                    <a href="{% url 'componente_list' %}" class="btn btn-secondary btn-block">
                                        <i class="fa fa-arrow-left"></i> Volver
                                    </a>
                                </div>
                            </div>
                            <br>
                            <table id="data" class="table table-striped table-responsive table-bordered dataTablesWidth">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Componente</th>
                                    <th>UNII</th>
                                    <th>Accion</th>
                                    <th>Fecha</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" charset="utf8" src="{% static 'datatables.net/js/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'datatables.net-bs4/js/dataTables.bootstrap4.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'datatables.net-colreorder/js/dataTables.colReorder.min.js' %}"></script>
    <script type="text/javascript" charset="utf8" src="{% static 'datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#data');
            var tableData = table.DataTable(
                {
                    "language": {
                        "url": "{% static 'js/datatable/language/es_ES.json' %}"
                    },
                    order: [[ 0, "asc" ]],
                    lengthMenu: [[10, 25, 50], [10, 25, 50]],
                    columnDefs: [
                        {
                            orderable: true,
                            searchable: true,
                            targets: [0, 3]
                        },
                        {
                            orederable: true,
                            searchable: true,
                            targets: [4]
                        },
                        {
                            orderable: false,
                            searchable: false,
                            className: "center",
                            targets: [5],
                            "defaultContent": "<div class=\"btn-group\" role=\"group\" aria-label=\"Acciones\">\n" +
                            "<button id=\"editar\" type=\"button\" class=\"btn btn-info\">\n" +
                            "<i class=\"fa fa-search\"></i>\n" +
                            "</button>\n" +
                            "</div>"
                        }
                    ],
                    searching: true,
                    processing: true,
                    serverSide: true,
                    stateSave: true,
                    ajax: "{% url 'componente_auditoria_data' %}"
                }
            );

            $("#search").on("keyup search input paste cut", function() {
                tableData.search(this.value).draw();
            });

            table.on("click", "#editar", function() {
                var dataTable = tableData.row( $(this).parents('tr') ).data();
                window.location = "{% url 'componente_auditoria_detail' 12345 %}".replace(/12345/, dataTable[0].toString());
            });
        });
    </script>
{% endblock %}