main/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from main import views as app_views


urlpatterns = [
    url(r'^$', app_views.home, name='home'),

    # Componentes
    url(r'^componentes/data/$', app_views.ComponenteJson.as_view(), name="componente_data"),
    url(r'^componentes/$', app_views.ComponenteList.as_view(), name="componente_list"),
    url(r'^componentes/create/$', app_views.ComponenteCreate.as_view(), name="componente_create"),
    url(r'^componentes/(?P<pk>\d+)/editar/$', app_views.ComponenteUpdate.as_view(), name="componente_update"),
    url(r'^componentes/eliminar/$', app_views.ComponenteDelete.as_view(), name="componente_delete"),

    # Auditoria de componentes
    url(r'^componentes/auditoria/data/$', app_views.ComponenteAuditoriaJson.as_view(),
        name="componente_auditoria_data"),
    url(r'^componentes/auditoria/$', app_views.ComponenteAuditoriaList.as_view(), name="componente_auditoria_list"),
    url(r'^componentes/auditoria/(?P<pk>\d+)/$', app_views.ComponenteAuditoriaDetail.as_view(),
        name="componente_auditoria_detail"),
]

perfiles/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from perfiles.views import PerfilEditarView
from avatar import urls as avatar_urls


urlpatterns = [
    url(r'^avatar/', include(avatar_urls)),
    url(r'^editar/', login_required(PerfilEditarView.as_view()), name='perfil_editar'),
    url(r'^$', login_required(TemplateView.as_view(template_name='perfiles/perfil.html')), name='perfil_home'),
]

proyecto/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from main import urls as app_urls
from perfiles import urls as perfil_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('two_factor.urls', 'two_factor')),
    url(r'^account/', include('allauth.urls')),
    url(r'', include(app_urls)),
    url(r'^profile/', include(perfil_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models/componente.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import ManyToManyField


class Componente(models.Model):
    TIPO_COMPONENTE = (
        (1, 'Activo'),
        (2, 'Excipiente'),
    )

    responsable = models.ForeignKey(User, related_name='componentes', verbose_name='Responsable')
    nombre_comercial = models.CharField(max_length=50, unique=True, verbose_name='Nombre Comercial')
    iupac = models.CharField(max_length=50, unique=True, verbose_name='IUPAC')
    unii = models.CharField(max_length=25, unique=True, verbose_name='UNII')
    formula = models.CharField(max_length=50, verbose_name='Formula')
    peso_molecular = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, verbose_name='Peso Molecular')
    biodisponibilidad = models.CharField(max_length=25, blank=True, null=True, verbose_name='Biodisponibilidad')
    union_proteica = models.CharField(max_length=25, blank=True, null=True, verbose_name='Union Proteica')
    metabolismo = models.CharField(max_length=25, blank=True, null=True, verbose_name='Metabolismo')
    vida_media = models.CharField(max_length=25, blank=True, null=True, verbose_name='Vida Media')
    excrecion = models.CharField(max_length=25, blank=True, null=True, verbose_name='Excrecion')
    via_admon = models.CharField(max_length=50, verbose_name='Via de Administracion')
    tipo = models.PositiveSmallIntegerField(choices=TIPO_COMPONENTE, verbose_name='Tipo')

    creado = models.DateTimeField(auto_now_add=True, verbose_name='Creado')
    fecha_firma = models.DateTimeField(auto_now=True, verbose_name='Fecha Firma')
    firma = models.TextField(blank=True, null=True, verbose_name='Firma Electronica')

    class Meta:
        app_label = 'main'
        verbose_name = 'Componente'
        verbose_name_plural = 'Componentes'

    def __str__(self):
        return '%s - %s' % (self.unii, self.nombre_comercial)

    def to_dict(self):
        opts = self._meta
        data = {}
        for f in opts.concrete_fields + opts.many_to_many:
            if isinstance(f, ManyToManyField):
                if self.pk is None:
                    data[f.name] = []
                else:
                    data[f.name] = list(f.value_from_object(self).values_list('pk', flat=True))
            else:
                data[f.name] = str(f.value_from_object(self))
        return data

perfiles/models.py
from django.db import models

# Create your models here.

perfiles/forms/perfil.py
from django import forms
from django.contrib.auth.models import User



class PerfilForm(forms.ModelForm):
    # fields para perfil
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

perfiles/views/perfil.py
from perfiles.forms import PerfilForm
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class PerfilEditarView(SuccessMessageMixin, UpdateView):
    template_name = 'perfiles/editar.html'
    form_class = PerfilForm
    model = User
    success_url = '/profile/'
    success_message = _('Profile updated successfully')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        # form.send_email()
        return super(PerfilEditarView, self).form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user

perfiles/templates/avatar/add.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}

{% block content %}
    <p>{% trans "Your current avatar: " %}</p>
    {% avatar user %}
    {% if not avatars %}
        <p>{% trans "You haven't uploaded an avatar yet. Please upload one now." %}</p>
    {% endif %}
    <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
        {{ upload_avatar_form.as_p }}
        <p>{% csrf_token %}<input type="submit" value="{% trans "Upload New Image" %}" /></p>
    </form>
{% endblock %}

perfiles/templates/avatar/avatar_tag.html
<img src="{{ url }}" alt="{{ alt }}" width="{{ size }}" height="{{ size }}" {% for key, value in kwargs.items %}{{key}}="{{value}}" {% endfor %}/>

perfiles/templates/avatar/base.html
{% extends "perfiles/base.html" %}

perfiles/templates/avatar/change.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load crispy_forms_tags %}
{% load static from staticfiles %}

{% block title %}
    Cambiar Avatar
{% endblock title %}

{% block content_header %}
    <!-- Breadcrumb -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Inicio</a></li>
        <li class="breadcrumb-item"><a href="{% url 'perfil_home' %}">Pefil</a></li>
        <li class="breadcrumb-item active">Cambiar Avatar</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="animated fadeIn">
        <div class="row">
            <div class="col">
                <form enctype="multipart/form-data" method="POST" action="">
                    <div class="card card-accent-warning">
                        <div class="card-header">
                            <strong>Cambiar mi Avatar</strong>
                        </div>
                        <div class="card-body">
                            <h3>{% trans "Select your avatar" %}</h3>
                            {% if not avatars %}
                                <p class="text-muted">No has subido un avator para seleccionar, por favor sube uno ahora.</p>
                            {% else %}
                                <form method="POST" action="{% url 'avatar_change' %}">
                                    <p class="text-muted">Clic en el avatar que deseas usar</p>
                                    {% csrf_token %}
                                    {{ primary_avatar_form | crispy }}
                                </form>
                            {% endif %}

                            <br>
                            <hr>

                            <p>O Sube una nueva imagen</p>
                            {% csrf_token %}
                            {{ upload_avatar_form | crispy }}
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Subir Imagen</button>
                            <a class="btn btn-secondary pull-right" href="{% url 'perfil_home' %}"> Cancelar</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function(){
            $('input[type=radio]').change(function(){
                $(this).parents('form').submit();
            });
        });
    </script>
{% endblock scripts %}

perfiles/templates/avatar/confirm_delete.html
{% extends "avatar/base.html" %}
{% load i18n avatar_tags %}
{% load crispy_forms_tags %}
{% load static from staticfiles %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/perfil.css' %}">
{% endblock styles %}

{% block content %}
    <div class="row">
        <div class="col-sm-9 well">
            <h1>Quitar avatar</h1>
            <hr>

            <p>{% trans "Please select the avatars that you would like to delete." %}</p>
            {% if not avatars %}
                {% url 'avatar_change' as avatar_change_url %}
                <p>{% blocktrans %}You have no avatars to delete. Please <a href="{{ avatar_change_url }}">upload one</a> now.{% endblocktrans %}</p>
            {% else %}
                <form method="POST" action="{% url 'avatar_delete' %}">
                    <ul class="list-unstyled">
                        {{ delete_avatar_form.as_ul }}
                    </ul>
                    <hr />
                    <p>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> {% trans "Delete These" %}</button>
                        <a class="btn btn-default" href="{% url 'perfil_home' %}"><i class="fa fa-arrow-left"></i> Volver</a>
                    </p>
                </form>
            {% endif %}

        </div>
        <div class="col-sm-3">
            <div class="well">
                <div class="row">
                    <br />
                    <div class="avatar col-sm-offset-1 col-sm-10">
                        {% avatar user 300 %}
                    </div>

                    <div class="col-sm-offset-1 col-sm-10">
                        <p class="text-center">
                            <strong>{{user.first_name}} {{user.last_name}}</strong> <br>
                            {{user.username}} <br> <br>
                            {{ user.perfil.get_tipo_display }}
                        </p>
                        <a href="{% url 'perfil_editar' %}" class="btn btn-warning full-width">
                            <i class="fa fa-user"></i>
                            {% trans "Edit my user" %}
                        </a>
                        <br />
                        <br />
                        {% if request.user.perfil %}

                            <a href="{% url 'perfil_avanzado' %}" class="btn btn-primary full-width">
                                <i class="fa fa-pencil"></i>
                                {% trans "Edit my profile" %}
                            </a>
                            <br />
                            <br />
                        {% endif %}
                        <a href="{% url 'account_logout' %}" class="btn btn-danger full-width">
                            {% trans "Sign Out" %}
                        </a>
                    </div>
                    <br />
                </div>
            </div>
        </div>
    </div>
{% endblock %}